### ISSUE TITLE
Validate database crashes on Arc SDE

### ISSUE THREAD

**Issue by hsnellen** [usgs/gems-tools-arcmap#52]
The following is a copy/paste of the error I ran into when trying to execute the "Validate database" tool on an Arc SDE on ArcMap.  

Executing: ValidateDatabase "Database Connections\Eden.sde" C:\Users\hsnellen\Desktop\test2 false false
Start Time: Mon Dec  7 14:25:07 2020
Running script ValidateDatabase...
GeMS_ValidateDatabase_Arc10.py, version of 30 November 2020
Looking at level 2 compliance
  scanning DataSources
  scanning DescriptionOfMapUnits
  scanning Glossary
  scanning ContactsAndFaults
  scanning MapUnitPolys
  checking GeologicMap to see if it has MUP and CAF feature classes
  checking topology of GeologicMap
Failed script ValidateDatabase...

Traceback (most recent call last):
  File "C:\Users\hsnellen\Downloads\gems-tools-arcmap-master (2)\gems-tools-arcmap-master\Scripts\GeMS_ValidateDatabase_Arc10.py", line 907, in <module>
    nTopoErrors = checkTopology(workdir,inGdb,outErrorsGdb,'GeologicMap',MUP,CAF,2)
  File "C:\Users\hsnellen\Downloads\gems-tools-arcmap-master (2)\gems-tools-arcmap-master\Scripts\GeMS_ValidateDatabase_Arc10.py", line 272, in checkTopology
    arcpy.Copy_management(inGdb+'/'+fd+'/'+MUP,outMup)
  File "c:\program files (x86)\arcgis\desktop10.6\arcpy\arcpy\management.py", line 4304, in Copy
    raise e
ExecuteError: ERROR 000260: Failed to copy Database Connections\Eden.sde/GeologicMap/Eden.DBO.MapUnitPolys into C:\Users\hsnellen\Desktop\test2\Eden_Validation.gdb\GeologicMap\Eden.DBO.MapUnitPolys
ERROR 000260: The table name is invalid.
Failed to execute (Copy).

Failed to execute (ValidateDatabase).
Failed at Mon Dec  7 14:27:20 2020 (Elapsed Time: 2 minutes 12 seconds)

**Comment by aazaff** [comment]
Just as some additional context, we are able to run the validate tool one equivalent databases that are saved locally as .gdbs. Presumably the problem here is related to connections with ArcSDE.

**Comment by ethoms-usgs** [comment]
The problem may be as simple as the fact that field names in file gdbs can't have dots in them. Because I don't have an SDE database to try this with and because I don't want to push changes for this problem until I know for sure, could you add these changes to lines 267 and 268 and try again?

```
outCaf = outFd+'/'+CAF.replace('.', '_')
outMup = outFd+'/'+MUP.replace('.', '_')
```

**Comment by aazaff** [comment]
We can do that, but sorry, lines 267 and 268 of which script? Maybe you could make a PR/branch here that we could download?

**Comment by aazaff** [comment]
Longer-term, we should discuss maybe giving you access to one of our ArcSDE servers for testing.

**Comment by ethoms-usgs** [comment]
Sorry, make the changes to GeMS_ValidateDatabase_Arc10.py

But, that's a good idea to push a branch. Haven't done that before. I will try it out

**Comment by ethoms-usgs** [comment]
Ok, the branch table-names-fix is there. The only changes are those two lines.

**Comment by aazaff** [comment]
Excellent @hsnellen can you please download the branch and test it out? Telegram me if you need instructions.

**Comment by hsnellen** [comment]
I've tested and it failed but with a new error:

Executing: ValidateDatabase "Database Connections\Vulture_Peak.sde" C:\Users\hsnellen\Desktop\test2 false false
Start Time: Wed Dec  9 13:09:31 2020
Running script ValidateDatabase...
GeMS_ValidateDatabase_Arc10.py, version of 30 November 2020
Looking at level 2 compliance
  scanning DataSources
  scanning DescriptionOfMapUnits
  scanning Glossary
  scanning ContactsAndFaults
  scanning MapUnitPolys
  checking GeologicMap to see if it has MUP and CAF feature classes
  checking topology of GeologicMap
Failed script ValidateDatabase...

Traceback (most recent call last):
  File "C:\Users\hsnellen\Downloads\gems-tools-arcmap-table-names-fix\gems-tools-arcmap-table-names-fix\Scripts\GeMS_ValidateDatabase_Arc10.py", line 907, in <module>
    nTopoErrors = checkTopology(workdir,inGdb,outErrorsGdb,'GeologicMap',MUP,CAF,2)
  File "C:\Users\hsnellen\Downloads\gems-tools-arcmap-table-names-fix\gems-tools-arcmap-table-names-fix\Scripts\GeMS_ValidateDatabase_Arc10.py", line 268, in checkTopology
    outMup = outFd+'/'+MUP('.', '_')
TypeError: 'unicode' object is not callable

Failed to execute (ValidateDatabase).
Failed at Wed Dec  9 13:11:13 2020 (Elapsed Time: 1 minutes 42 seconds)

**Comment by ethoms-usgs** [comment]
Oh boy, I am sorry. There should be the .replace() function after MUP. It's been changed.

**Comment by hsnellen** [comment]
I've re-downloaded, and it has failed but with a different error as the first one.  I'll paste below:

Executing: ValidateDatabase "Database Connections\Vulture_Peak.sde" C:\Users\hsnellen\Desktop\test2\vulturepeak false false
Start Time: Wed Dec  9 14:33:53 2020
Running script ValidateDatabase...
GeMS_ValidateDatabase_Arc10.py, version of 30 November 2020
Looking at level 2 compliance
  scanning DataSources
  scanning DescriptionOfMapUnits
  scanning Glossary
  scanning ContactsAndFaults
  scanning MapUnitPolys
  checking GeologicMap to see if it has MUP and CAF feature classes
  checking topology of GeologicMap
    creating C:\Users\hsnellen\Desktop\test2\vulturepeak/Vulture_Peak_Validation.gdb/GeologicMap/GeologicMap_topology
    adding level 2 rules to topology:
      Must Not Overlap (Area)
      Must Not Have Gaps (Area)
      Boundary Must Be Covered By (Area-Line)
    validating topology
    exporting topology errors
  getting unused, missing, and duplicated key values
Looking at level 3 compliance
  scanning Vulture_Peak.DBO.DataSources
  scanning Vulture_Peak.DBO.StandardLithology
  scanning Vulture_Peak.DBO.Notes
  scanning Vulture_Peak.DBO.Glossary
  scanning Vulture_Peak.DBO.SysInfo
  scanning Vulture_Peak.DBO.GeologicEvents
  scanning Vulture_Peak.DBO.ExtendedAttributes
  scanning Vulture_Peak.DBO.DescriptionOfMapUnits
  scanning Vulture_Peak.dbo.SDE_compress_log
Failed script ValidateDatabase...

Traceback (most recent call last):
  File "C:\Users\hsnellen\Downloads\gems-tools-arcmap-table-names-fix\gems-tools-arcmap-table-names-fix\Scripts\GeMS_ValidateDatabase_Arc10.py", line 944, in <module>
    mapUnits = scanTable(tb)
  File "C:\Users\hsnellen\Downloads\gems-tools-arcmap-table-names-fix\gems-tools-arcmap-table-names-fix\Scripts\GeMS_ValidateDatabase_Arc10.py", line 725, in scanTable
    oxxft = '<span class="table">'+table+'</span>, field <span class="field">'+fieldNames[i]+'</span>, ObjectID '+str(row[objIdIndex])
UnboundLocalError: local variable 'objIdIndex' referenced before assignment

Failed to execute (ValidateDatabase).
Failed at Wed Dec  9 14:37:04 2020 (Elapsed Time: 3 minutes 10 seconds)

**Comment by ethoms-usgs** [comment]
Ok, thanks for trying that out. 
As you can tell, there are bigger problems. This is something I have wondered about for a while; if this tool would work with SDE databases and now I can see some of the issues, namely the qualified table names and lower vs upper case field names; not hard things to write against but there are, potentially, numerous changes to make.

Andrew, could you look into getting me access to one of your servers? I will also ask around the USGS and if one turns up, I will go with that.

I think making sure we can get this tool to work with SDE would be a big step forward.

**Comment by aazaff** [comment]
Thanks for your timely response on this. It is certainly essential for our GeMS workflow moving forward that this work with SDE and I assume other surveys must be in a similar situation, so thanks for making it a priority.

I would normally be be more than happy to give you access to one of our SDE servers for testing/dev, however, our sysadmin just quit a couple weeks ago. This means that what would normally be a semi-trivial process is now kind of complicated for us because of the firewall/network issues involved (hence why I said "longer term" above). 

We will look into it, but it may be better to look towards another survey or elsewhere in the USGS as you suggest. I know the next CDEFG meeting is this Monday, and you might be able to ask then. I suspect at least some of them use SDE.

**Comment by ethoms-usgs** [comment]
Sure thing. I have started queries. I would only take you up on the offer if it was easy!
