### ISSUE TITLE
Translate to Shapefiles fail

### ISSUE THREAD

**Issue by stub0035** [usgs/gems-tools-arcmap#85]
While running this tool it fails when it's trying to read the DescriptionOfMapUnits and converting it to a csv file.  I'm also having issues running this tool in ArcPro (see issues in gems-tools-arcpro).  My database is level 3 compliant with full Metadata.  Here is my Fail: 

 Dumping DescriptionOfMapUnits.csv...
Failed script TranslateToShape...

Traceback (most recent call last):
  File "J:\ArcGIS_scripts\GeMS\gems-tools-arcmap-1.6.11\gems-tools-arcmap-1.6.11\Scripts\GeMS_TranslateToShape_Arc10.py", line 461, in <module>
    main(newgdb, ows, gdb)
  File "J:\ArcGIS_scripts\GeMS\gems-tools-arcmap-1.6.11\gems-tools-arcmap-1.6.11\Scripts\GeMS_TranslateToShape_Arc10.py", line 439, in main
    dumpTable(tbl, outName, False, outputDir, logfile, isOpen, tbl)
  File "J:\ArcGIS_scripts\GeMS\gems-tools-arcmap-1.6.11\gems-tools-arcmap-1.6.11\Scripts\GeMS_TranslateToShape_Arc10.py", line 189, in dumpTable
    out_field.name = remapFieldName(fName)
  File "J:\ArcGIS_scripts\GeMS\gems-tools-arcmap-1.6.11\gems-tools-arcmap-1.6.11\Scripts\GeMS_TranslateToShape_Arc10.py", line 126, in remapFieldName
    j = j+1
UnboundLocalError: local variable 'j' referenced before assignment

Failed to execute (TranslateToShape).
Failed at Thu Feb 10 10:51:53 2022 (Elapsed Time: 46 minutes 25 seconds)

![image](https://user-images.githubusercontent.com/8901908/153494478-3e856d48-c68a-4562-b3c3-efcc50d45e50.png)

**Comment by ethoms-usgs** [comment]
Have you added any extra non-GeMS fields to DescriptionOfMapUnits?

**Comment by stub0035** [comment]
Yes! Is that the issue?

**Comment by stub0035** [comment]
I have an additional 12 fields in the DescriptionOfMapUnits.  I do have
alisis for the fields but so do the default fields.  Would you like me to
send my gdb to you?  Thanks for your help!

**Comment by ethoms-usgs** [comment]
Sure, send the gdb.
